name: Python Workflow
on:
    workflow_dispatch:    

jobs:
    run_python_script:
        environment: NonProd
        runs-on: self-hosted
        steps:
            - name: Check out the repository
              uses: actions/checkout@v5.0.0

            - name: Set up Python
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.12.10'

            - name: Install and/or Upgrade pip
              run: |
                python -m pip install --upgrade pip --user
                echo "pip version used is: $(pip --version)"
              
            - name: Install pipx and ensure it is in the PATH environment variable
              run: |
                python -m pip install pipx --user
                pipx ensurepath
                echo "pipx version used is: $(pipx --version)"

            - name: Install poetry
              run: |
                pipx install poetry
                echo "poetry version used is: $(poetry --version)"

            - name: Install project dependencies
              run: poetry install

            - name: Logging secrets
              run: |
                echo "client_id is ${{ secrets.CLIENT_ID }}"
                echo "client_secret is ${{ secrets.CLIENT_SECRET }}"

            - name: Run Python script
              run: poetry run python script.py --client-id "${{ secrets.CLIENT_ID }}" --client-secret "${{ secrets.CLIENT_SECRET }}"
    