name: Python Workflow
on:
    workflow_dispatch:    

jobs:
    run_python_script:
        runs-on: self-hosted
        steps:
            - name: Check out the repository
              uses: actions/checkout@v5.0.0

            - name: Set up Python
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.12.10'

            - name: Install and/or Upgrade pip
              run: |
                python -m pip install --upgrade pip --user
                echo "pip version used is: $(pip --version)"
              
            - name: Install pipx
              run: python -m pip install pipx --user

            - name: Ensure pipx is in the PATH Environment Variable
              run: |
                pipx ensurepath
                echo "pipx version used is: $(pipx --version)"

            - name: Install poetry
              run: |
                pipx install poetry
                echo "poetry version used is: $(poetry --version)"

            - name: Install project dependencies
              run: poetry run install

            - name: Run Python script
              run: python script.py
            
    